### ISSUE TITLE
[prettier-plugin-glsl] error running with pnpm

### ISSUE THREAD

**Issue by disambiguator** [NaridaL/glsl-language-toolkit#10]
I recently attempted to convert a repo of mine to `pnpm`, but get this error when doing so.

```
> prettier --write shader.frag

shader.frag
[error] Couldn't resolve parser "glsl-parser"
```

I made a minimum reproduction case here.  https://github.com/disambiguator/pnpm-prettier-glsl/tree/switch-to-pnpm

**Comment by NaridaL** [comment]
I don't think this is an issue which can be fixed by this plugin. The plugin just relies on the default prettier plugin loading mechanism.

Have you tried the workarounds in https://github.com/sveltejs/prettier-plugin-svelte/issues/155 ? 

See also https://github.com/prettier/prettier/pull/9167 .

In general, I've found the npm alternatives are never worth the additional hassle, even if npm isn't perfect, but of yourse YMMV 🤷 .

**Comment by disambiguator** [comment]
Ah rad, you're right.This does solve it!

For posterity, changing `.prettierrc.js` to this fixes the problem.
```
module.exports = {
  overrides: [{ files: ["*.frag"], options: { parser: "glsl-parser" } }],
  plugins: ["prettier-plugin-glsl"],
};
```
